// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.MonitoringV2.Inputs
{

    public sealed class AlertsArgs : global::Pulumi.ResourceArgs
    {
        [Input("email", required: true)]
        private InputList<string>? _email;

        /// <summary>
        /// An email to notify on an alert trigger.
        /// </summary>
        public InputList<string> Email
        {
            get => _email ?? (_email = new InputList<string>());
            set => _email = value;
        }

        [Input("slack", required: true)]
        private InputList<Inputs.SlackDetailsArgs>? _slack;

        /// <summary>
        /// Slack integration details.
        /// </summary>
        public InputList<Inputs.SlackDetailsArgs> Slack
        {
            get => _slack ?? (_slack = new InputList<Inputs.SlackDetailsArgs>());
            set => _slack = value;
        }

        public AlertsArgs()
        {
        }
        public static new AlertsArgs Empty => new AlertsArgs();
    }
}
