// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.AppsV2.Outputs
{

    [OutputType]
    public sealed class AppResponse
    {
        /// <summary>
        /// An application's configuration and status.
        /// </summary>
        public readonly Outputs.App? App;

        [OutputConstructor]
        private AppResponse(Outputs.App? app)
        {
            App = app;
        }
    }
}
