// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.AccountV2
{
    /// <summary>
    /// This value is one of "active", "warning" or "locked".
    /// </summary>
    [EnumType]
    public readonly struct AccountStatus : IEquatable<AccountStatus>
    {
        private readonly string _value;

        private AccountStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static AccountStatus Active { get; } = new AccountStatus("active");
        public static AccountStatus Warning { get; } = new AccountStatus("warning");
        public static AccountStatus Locked { get; } = new AccountStatus("locked");

        public static bool operator ==(AccountStatus left, AccountStatus right) => left.Equals(right);
        public static bool operator !=(AccountStatus left, AccountStatus right) => !left.Equals(right);

        public static explicit operator string(AccountStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is AccountStatus other && Equals(other);
        public bool Equals(AccountStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
