// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.ActionsV2
{
    public static class GetAction
    {
        public static Task<GetActionResult> InvokeAsync(GetActionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetActionResult>("digitalocean-native:actions/v2:getAction", args ?? new GetActionArgs(), options.WithDefaults());

        public static Output<GetActionResult> Invoke(GetActionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetActionResult>("digitalocean-native:actions/v2:getAction", args ?? new GetActionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetActionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A unique numeric ID that can be used to identify and reference an action.
        /// </summary>
        [Input("actionId", required: true)]
        public string ActionId { get; set; } = null!;

        public GetActionArgs()
        {
        }
        public static new GetActionArgs Empty => new GetActionArgs();
    }

    public sealed class GetActionInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A unique numeric ID that can be used to identify and reference an action.
        /// </summary>
        [Input("actionId", required: true)]
        public Input<string> ActionId { get; set; } = null!;

        public GetActionInvokeArgs()
        {
        }
        public static new GetActionInvokeArgs Empty => new GetActionInvokeArgs();
    }


    [OutputType]
    public sealed class GetActionResult
    {
        public readonly Outputs.GetActionProperties Items;

        [OutputConstructor]
        private GetActionResult(Outputs.GetActionProperties items)
        {
            Items = items;
        }
    }
}
