// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getAppsMetricsBandwidthDaily(args: GetAppsMetricsBandwidthDailyArgs, opts?: pulumi.InvokeOptions): Promise<GetAppsMetricsBandwidthDailyResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("digitalocean-native:apps/v2:getAppsMetricsBandwidthDaily", {
        "appId": args.appId,
    }, opts);
}

export interface GetAppsMetricsBandwidthDailyArgs {
    /**
     * The app ID
     */
    appId: string;
}

export interface GetAppsMetricsBandwidthDailyResult {
    readonly items: outputs.apps.v2.AppMetricsBandwidthUsage;
}
export function getAppsMetricsBandwidthDailyOutput(args: GetAppsMetricsBandwidthDailyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAppsMetricsBandwidthDailyResult> {
    return pulumi.output(args).apply((a: any) => getAppsMetricsBandwidthDaily(a, opts))
}

export interface GetAppsMetricsBandwidthDailyOutputArgs {
    /**
     * The app ID
     */
    appId: pulumi.Input<string>;
}
