# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload, Awaitable
from ... import _utilities
from . import outputs

__all__ = [
    'GetFunctionsTriggerProperties',
    'AwaitableGetFunctionsTriggerProperties',
    'get_functions_trigger',
    'get_functions_trigger_output',
]

@pulumi.output_type
class GetFunctionsTriggerProperties:
    def __init__(__self__, trigger=None):
        if trigger and not isinstance(trigger, dict):
            raise TypeError("Expected argument 'trigger' to be a dict")
        pulumi.set(__self__, "trigger", trigger)

    @property
    @pulumi.getter
    def trigger(self) -> Optional['outputs.TriggerInfo']:
        return pulumi.get(self, "trigger")


class AwaitableGetFunctionsTriggerProperties(GetFunctionsTriggerProperties):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetFunctionsTriggerProperties(
            trigger=self.trigger)


def get_functions_trigger(namespace_id: Optional[str] = None,
                          trigger_name: Optional[str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetFunctionsTriggerProperties:
    """
    Use this data source to access information about an existing resource.

    :param str namespace_id: The ID of the namespace to be managed.
    :param str trigger_name: The name of the trigger to be managed.
    """
    __args__ = dict()
    __args__['namespaceId'] = namespace_id
    __args__['triggerName'] = trigger_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('digitalocean-native:functions/v2:getFunctionsTrigger', __args__, opts=opts, typ=GetFunctionsTriggerProperties).value

    return AwaitableGetFunctionsTriggerProperties(
        trigger=pulumi.get(__ret__, 'trigger'))


@_utilities.lift_output_func(get_functions_trigger)
def get_functions_trigger_output(namespace_id: Optional[pulumi.Input[str]] = None,
                                 trigger_name: Optional[pulumi.Input[str]] = None,
                                 opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetFunctionsTriggerProperties]:
    """
    Use this data source to access information about an existing resource.

    :param str namespace_id: The ID of the namespace to be managed.
    :param str trigger_name: The name of the trigger to be managed.
    """
    ...
