# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'BillingHistoryType',
]


@pulumi.type_token("digitalocean-native:customers/v2:BillingHistoryType")
class BillingHistoryType(_builtins.str, Enum):
    """
    Type of billing history entry.
    """
    ACH_FAILURE = "ACHFailure"
    ADJUSTMENT = "Adjustment"
    ATTEMPT_FAILED = "AttemptFailed"
    CHARGEBACK = "Chargeback"
    CREDIT = "Credit"
    CREDIT_EXPIRATION = "CreditExpiration"
    INVOICE = "Invoice"
    PAYMENT = "Payment"
    REFUND = "Refund"
    REVERSAL = "Reversal"
