# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'CdnEndpointTtl',
    'Ttl',
]


@pulumi.type_token("digitalocean-native:cdn/v2:CdnEndpointTtl")
class CdnEndpointTtl(_builtins.int, Enum):
    """
    The amount of time the content is cached by the CDN's edge servers in seconds. TTL must be one of 60, 600, 3600, 86400, or 604800. Defaults to 3600 (one hour) when excluded.
    """
    CDN_ENDPOINT_TTL_D_FLOAT64_60_ = 60
    CDN_ENDPOINT_TTL_D_FLOAT64_600_ = 600
    CDN_ENDPOINT_TTL_D_FLOAT64_3600_ = 3600
    CDN_ENDPOINT_TTL_D_FLOAT64_86400_ = 86400
    CDN_ENDPOINT_TTL_D_FLOAT64_604800_ = 604800


@pulumi.type_token("digitalocean-native:cdn/v2:Ttl")
class Ttl(_builtins.int, Enum):
    """
    The amount of time the content is cached by the CDN's edge servers in seconds. TTL must be one of 60, 600, 3600, 86400, or 604800. Defaults to 3600 (one hour) when excluded.
    """
    TTL_D_FLOAT64_60_ = 60
    TTL_D_FLOAT64_600_ = 600
    TTL_D_FLOAT64_3600_ = 3600
    TTL_D_FLOAT64_86400_ = 86400
    TTL_D_FLOAT64_604800_ = 604800
