// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.DigitalOceanNative.CdnV2
{
    /// <summary>
    /// The amount of time the content is cached by the CDN's edge servers in seconds. TTL must be one of 60, 600, 3600, 86400, or 604800. Defaults to 3600 (one hour) when excluded.
    /// </summary>
    public enum CdnEndpointTtl
    {
        CdnEndpointTtl_d_float64_60_ = 60,
        CdnEndpointTtl_d_float64_600_ = 600,
        CdnEndpointTtl_d_float64_3600_ = 3600,
        CdnEndpointTtl_d_float64_86400_ = 86400,
        CdnEndpointTtl_d_float64_604800_ = 604800,
    }
}
