// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.KubernetesV2.Outputs
{

    [OutputType]
    public sealed class ClusterlintResultsDiagnosticsItemProperties
    {
        /// <summary>
        /// The clusterlint check that resulted in the diagnostic.
        /// </summary>
        public readonly string? CheckName;
        /// <summary>
        /// Feedback about the object for users to fix.
        /// </summary>
        public readonly string? Message;
        /// <summary>
        /// Metadata about the Kubernetes API object the diagnostic is reported on.
        /// </summary>
        public readonly Outputs.ClusterlintResultsDiagnosticsItemPropertiesObjectProperties? Object;
        /// <summary>
        /// Can be one of error, warning or suggestion.
        /// </summary>
        public readonly string? Severity;

        [OutputConstructor]
        private ClusterlintResultsDiagnosticsItemProperties(
            string? checkName,

            string? message,

            Outputs.ClusterlintResultsDiagnosticsItemPropertiesObjectProperties? @object,

            string? severity)
        {
            CheckName = checkName;
            Message = message;
            Object = @object;
            Severity = severity;
        }
    }
}
