// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.KubernetesV2.Outputs
{

    [OutputType]
    public sealed class Node
    {
        /// <summary>
        /// A time value given in ISO8601 combined date and time format that represents when the node was created.
        /// </summary>
        public readonly string? CreatedAt;
        /// <summary>
        /// The ID of the Droplet used for the worker node.
        /// </summary>
        public readonly string? DropletId;
        /// <summary>
        /// A unique ID that can be used to identify and reference the node.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// An automatically generated, human-readable name for the node.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// An object containing a `state` attribute whose value is set to a string indicating the current status of the node.
        /// </summary>
        public readonly Outputs.NodeStatusProperties? Status;
        /// <summary>
        /// A time value given in ISO8601 combined date and time format that represents when the node was last updated.
        /// </summary>
        public readonly string? UpdatedAt;

        [OutputConstructor]
        private Node(
            string? createdAt,

            string? dropletId,

            string? id,

            string? name,

            Outputs.NodeStatusProperties? status,

            string? updatedAt)
        {
            CreatedAt = createdAt;
            DropletId = dropletId;
            Id = id;
            Name = name;
            Status = status;
            UpdatedAt = updatedAt;
        }
    }
}
