# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'ListReservedIPsResult',
    'AwaitableListReservedIPsResult',
    'list_reserved_ips',
    'list_reserved_ips_output',
]

@pulumi.output_type
class ListReservedIPsResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.ListReservedIPsItems':
        return pulumi.get(self, "items")


class AwaitableListReservedIPsResult(ListReservedIPsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListReservedIPsResult(
            items=self.items)


def list_reserved_ips(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListReservedIPsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('digitalocean-native:reserved_ips/v2:listReservedIPs', __args__, opts=opts, typ=ListReservedIPsResult).value

    return AwaitableListReservedIPsResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(list_reserved_ips)
def list_reserved_ips_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[ListReservedIPsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
