// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.MonitoringV2
{
    public static class GetMonitoringDropletCpuMetric
    {
        public static Task<Outputs.Metrics> InvokeAsync(GetMonitoringDropletCpuMetricArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.Metrics>("digitalocean-native:monitoring/v2:getMonitoringDropletCpuMetric", args ?? new GetMonitoringDropletCpuMetricArgs(), options.WithDefaults());

        public static Output<Outputs.Metrics> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.Metrics>("digitalocean-native:monitoring/v2:getMonitoringDropletCpuMetric", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetMonitoringDropletCpuMetricArgs : global::Pulumi.InvokeArgs
    {
        public GetMonitoringDropletCpuMetricArgs()
        {
        }
        public static new GetMonitoringDropletCpuMetricArgs Empty => new GetMonitoringDropletCpuMetricArgs();
    }
}
