// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.MonitoringV2
{
    public static class GetMonitoringDropletCpuMetric
    {
        public static Task<GetMonitoringDropletCpuMetricResult> InvokeAsync(GetMonitoringDropletCpuMetricArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetMonitoringDropletCpuMetricResult>("digitalocean-native:monitoring/v2:getMonitoringDropletCpuMetric", args ?? new GetMonitoringDropletCpuMetricArgs(), options.WithDefaults());

        public static Output<GetMonitoringDropletCpuMetricResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetMonitoringDropletCpuMetricResult>("digitalocean-native:monitoring/v2:getMonitoringDropletCpuMetric", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetMonitoringDropletCpuMetricArgs : global::Pulumi.InvokeArgs
    {
        public GetMonitoringDropletCpuMetricArgs()
        {
        }
        public static new GetMonitoringDropletCpuMetricArgs Empty => new GetMonitoringDropletCpuMetricArgs();
    }


    [OutputType]
    public sealed class GetMonitoringDropletCpuMetricResult
    {
        public readonly Outputs.Metrics Items;

        [OutputConstructor]
        private GetMonitoringDropletCpuMetricResult(Outputs.Metrics items)
        {
            Items = items;
        }
    }
}
