// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.MonitoringV2
{
    public static class GetMonitoringDropletMemoryCachedMetric
    {
        public static Task<Outputs.Metrics> InvokeAsync(GetMonitoringDropletMemoryCachedMetricArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.Metrics>("digitalocean-native:monitoring/v2:getMonitoringDropletMemoryCachedMetric", args ?? new GetMonitoringDropletMemoryCachedMetricArgs(), options.WithDefaults());

        public static Output<Outputs.Metrics> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.Metrics>("digitalocean-native:monitoring/v2:getMonitoringDropletMemoryCachedMetric", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetMonitoringDropletMemoryCachedMetricArgs : global::Pulumi.InvokeArgs
    {
        public GetMonitoringDropletMemoryCachedMetricArgs()
        {
        }
        public static new GetMonitoringDropletMemoryCachedMetricArgs Empty => new GetMonitoringDropletMemoryCachedMetricArgs();
    }
}
