# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs

__all__ = [
    'GetAppsLogsActiveDeploymentAggregateResult',
    'AwaitableGetAppsLogsActiveDeploymentAggregateResult',
    'get_apps_logs_active_deployment_aggregate',
    'get_apps_logs_active_deployment_aggregate_output',
]

@pulumi.output_type
class GetAppsLogsActiveDeploymentAggregateResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.AppsGetLogsResponse':
        return pulumi.get(self, "items")


class AwaitableGetAppsLogsActiveDeploymentAggregateResult(GetAppsLogsActiveDeploymentAggregateResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAppsLogsActiveDeploymentAggregateResult(
            items=self.items)


def get_apps_logs_active_deployment_aggregate(app_id: Optional[str] = None,
                                              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAppsLogsActiveDeploymentAggregateResult:
    """
    Use this data source to access information about an existing resource.

    :param str app_id: The app ID
    """
    __args__ = dict()
    __args__['appId'] = app_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('digitalocean-native:apps/v2:getAppsLogsActiveDeploymentAggregate', __args__, opts=opts, typ=GetAppsLogsActiveDeploymentAggregateResult).value

    return AwaitableGetAppsLogsActiveDeploymentAggregateResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(get_apps_logs_active_deployment_aggregate)
def get_apps_logs_active_deployment_aggregate_output(app_id: Optional[pulumi.Input[str]] = None,
                                                     opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetAppsLogsActiveDeploymentAggregateResult]:
    """
    Use this data source to access information about an existing resource.

    :param str app_id: The app ID
    """
    ...
