// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getMonitoringDropletFilesystemSizeMetric(args?: GetMonitoringDropletFilesystemSizeMetricArgs, opts?: pulumi.InvokeOptions): Promise<GetMonitoringDropletFilesystemSizeMetricResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("digitalocean-native:monitoring/v2:getMonitoringDropletFilesystemSizeMetric", {
    }, opts);
}

export interface GetMonitoringDropletFilesystemSizeMetricArgs {
}

export interface GetMonitoringDropletFilesystemSizeMetricResult {
    readonly items: outputs.monitoring.v2.Metrics;
}
export function getMonitoringDropletFilesystemSizeMetricOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetMonitoringDropletFilesystemSizeMetricResult> {
    return pulumi.output(getMonitoringDropletFilesystemSizeMetric(opts))
}
