// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.UptimeV2.Outputs
{

    [OutputType]
    public sealed class ListUptimeChecksItems
    {
        public readonly ImmutableArray<Outputs.Check> Checks;
        public readonly Outputs.PageLinks? Links;
        public readonly Outputs.MetaMeta MetaValue;

        [OutputConstructor]
        private ListUptimeChecksItems(
            ImmutableArray<Outputs.Check> checks,

            Outputs.PageLinks? links,

            Outputs.MetaMeta meta)
        {
            Checks = checks;
            Links = links;
            MetaValue = meta;
        }
    }
}
