// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.LoadBalancersV2.Inputs
{

    /// <summary>
    /// An object specifying allow and deny rules to control traffic to the load balancer.
    /// </summary>
    public sealed class LbFirewallArgs : global::Pulumi.ResourceArgs
    {
        [Input("allow")]
        private InputList<string>? _allow;

        /// <summary>
        /// the rules for allowing traffic to the load balancer (in the form 'ip:1.2.3.4' or 'cidr:1.2.0.0/16')
        /// </summary>
        public InputList<string> Allow
        {
            get => _allow ?? (_allow = new InputList<string>());
            set => _allow = value;
        }

        [Input("deny")]
        private InputList<string>? _deny;

        /// <summary>
        /// the rules for denying traffic to the load balancer (in the form 'ip:1.2.3.4' or 'cidr:1.2.0.0/16')
        /// </summary>
        public InputList<string> Deny
        {
            get => _deny ?? (_deny = new InputList<string>());
            set => _deny = value;
        }

        public LbFirewallArgs()
        {
        }
        public static new LbFirewallArgs Empty => new LbFirewallArgs();
    }
}
