// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function listProjectsResourcesDefault(args?: ListProjectsResourcesDefaultArgs, opts?: pulumi.InvokeOptions): Promise<ListProjectsResourcesDefaultResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("digitalocean-native:projects/v2:listProjectsResourcesDefault", {
    }, opts);
}

export interface ListProjectsResourcesDefaultArgs {
}

export interface ListProjectsResourcesDefaultResult {
    readonly items: outputs.projects.v2.ListProjectsResourcesDefault;
}
export function listProjectsResourcesDefaultOutput(opts?: pulumi.InvokeOptions): pulumi.Output<ListProjectsResourcesDefaultResult> {
    return pulumi.output(listProjectsResourcesDefault(opts))
}
