// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.FirewallsV2
{
    [DigitalOceanNativeResourceType("digitalocean-native:firewalls/v2:FirewallsAssignDroplets")]
    public partial class FirewallsAssignDroplets : global::Pulumi.CustomResource
    {
        /// <summary>
        /// An array containing the IDs of the Droplets to be assigned to the firewall.
        /// </summary>
        [Output("dropletIds")]
        public Output<ImmutableArray<int>> DropletIds { get; private set; } = null!;


        /// <summary>
        /// Create a FirewallsAssignDroplets resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FirewallsAssignDroplets(string name, FirewallsAssignDropletsArgs args, CustomResourceOptions? options = null)
            : base("digitalocean-native:firewalls/v2:FirewallsAssignDroplets", name, args ?? new FirewallsAssignDropletsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FirewallsAssignDroplets(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("digitalocean-native:firewalls/v2:FirewallsAssignDroplets", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-digitalocean-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FirewallsAssignDroplets resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FirewallsAssignDroplets Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new FirewallsAssignDroplets(name, id, options);
        }
    }

    public sealed class FirewallsAssignDropletsArgs : global::Pulumi.ResourceArgs
    {
        [Input("dropletIds", required: true)]
        private InputList<int>? _dropletIds;

        /// <summary>
        /// An array containing the IDs of the Droplets to be assigned to the firewall.
        /// </summary>
        public InputList<int> DropletIds
        {
            get => _dropletIds ?? (_dropletIds = new InputList<int>());
            set => _dropletIds = value;
        }

        /// <summary>
        /// A unique ID that can be used to identify and reference a firewall.
        /// </summary>
        [Input("firewallId")]
        public Input<string>? FirewallId { get; set; }

        public FirewallsAssignDropletsArgs()
        {
        }
        public static new FirewallsAssignDropletsArgs Empty => new FirewallsAssignDropletsArgs();
    }
}
