// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-digitalocean-native/sdk/go/dgtlocn/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAppsInstanceSize(ctx *pulumi.Context, args *GetAppsInstanceSizeArgs, opts ...pulumi.InvokeOption) (*GetAppsInstanceSizeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAppsInstanceSizeResult
	err := ctx.Invoke("digitalocean-native:apps/v2:getAppsInstanceSize", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type GetAppsInstanceSizeArgs struct {
	// The slug of the instance size
	Slug string `pulumi:"slug"`
}

type GetAppsInstanceSizeResult struct {
	InstanceSize *AppsInstanceSize `pulumi:"instanceSize"`
}

// Defaults sets the appropriate defaults for GetAppsInstanceSizeResult
func (val *GetAppsInstanceSizeResult) Defaults() *GetAppsInstanceSizeResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.InstanceSize = tmp.InstanceSize.Defaults()

	return &tmp
}
func GetAppsInstanceSizeOutput(ctx *pulumi.Context, args GetAppsInstanceSizeOutputArgs, opts ...pulumi.InvokeOption) GetAppsInstanceSizeResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetAppsInstanceSizeResultOutput, error) {
			args := v.(GetAppsInstanceSizeArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("digitalocean-native:apps/v2:getAppsInstanceSize", args, GetAppsInstanceSizeResultOutput{}, options).(GetAppsInstanceSizeResultOutput), nil
		}).(GetAppsInstanceSizeResultOutput)
}

type GetAppsInstanceSizeOutputArgs struct {
	// The slug of the instance size
	Slug pulumi.StringInput `pulumi:"slug"`
}

func (GetAppsInstanceSizeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAppsInstanceSizeArgs)(nil)).Elem()
}

type GetAppsInstanceSizeResultOutput struct{ *pulumi.OutputState }

func (GetAppsInstanceSizeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAppsInstanceSizeResult)(nil)).Elem()
}

func (o GetAppsInstanceSizeResultOutput) ToGetAppsInstanceSizeResultOutput() GetAppsInstanceSizeResultOutput {
	return o
}

func (o GetAppsInstanceSizeResultOutput) ToGetAppsInstanceSizeResultOutputWithContext(ctx context.Context) GetAppsInstanceSizeResultOutput {
	return o
}

func (o GetAppsInstanceSizeResultOutput) InstanceSize() AppsInstanceSizePtrOutput {
	return o.ApplyT(func(v GetAppsInstanceSizeResult) *AppsInstanceSize { return v.InstanceSize }).(AppsInstanceSizePtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAppsInstanceSizeResultOutput{})
}
