// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.DatabasesV2.Outputs
{

    [OutputType]
    public sealed class ConnectionPools
    {
        /// <summary>
        /// An array of connection pool objects.
        /// </summary>
        public readonly ImmutableArray<Outputs.ConnectionPool> Pools;

        [OutputConstructor]
        private ConnectionPools(ImmutableArray<Outputs.ConnectionPool> pools)
        {
            Pools = pools;
        }
    }
}
