# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs

__all__ = [
    'ListDatabasesBackupsResult',
    'AwaitableListDatabasesBackupsResult',
    'list_databases_backups',
    'list_databases_backups_output',
]

@pulumi.output_type
class ListDatabasesBackupsResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.ListDatabasesBackupsProperties':
        return pulumi.get(self, "items")


class AwaitableListDatabasesBackupsResult(ListDatabasesBackupsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListDatabasesBackupsResult(
            items=self.items)


def list_databases_backups(database_cluster_uuid: Optional[str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListDatabasesBackupsResult:
    """
    Use this data source to access information about an existing resource.

    :param str database_cluster_uuid: A unique identifier for a database cluster.
    """
    __args__ = dict()
    __args__['databaseClusterUuid'] = database_cluster_uuid
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('digitalocean-native:databases/v2:listDatabasesBackups', __args__, opts=opts, typ=ListDatabasesBackupsResult).value

    return AwaitableListDatabasesBackupsResult(
        items=pulumi.get(__ret__, 'items'))


@_utilities.lift_output_func(list_databases_backups)
def list_databases_backups_output(database_cluster_uuid: Optional[pulumi.Input[str]] = None,
                                  opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[ListDatabasesBackupsResult]:
    """
    Use this data source to access information about an existing resource.

    :param str database_cluster_uuid: A unique identifier for a database cluster.
    """
    ...
