// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-digitalocean-native/sdk/go/dgtlocn/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetMonitoringDropletMemoryCachedMetric(ctx *pulumi.Context, args *GetMonitoringDropletMemoryCachedMetricArgs, opts ...pulumi.InvokeOption) (*GetMonitoringDropletMemoryCachedMetricResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetMonitoringDropletMemoryCachedMetricResult
	err := ctx.Invoke("digitalocean-native:monitoring/v2:getMonitoringDropletMemoryCachedMetric", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetMonitoringDropletMemoryCachedMetricArgs struct {
}

type GetMonitoringDropletMemoryCachedMetricResult struct {
	Items Metrics `pulumi:"items"`
}

func GetMonitoringDropletMemoryCachedMetricOutput(ctx *pulumi.Context, args GetMonitoringDropletMemoryCachedMetricOutputArgs, opts ...pulumi.InvokeOption) GetMonitoringDropletMemoryCachedMetricResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetMonitoringDropletMemoryCachedMetricResult, error) {
			args := v.(GetMonitoringDropletMemoryCachedMetricArgs)
			r, err := GetMonitoringDropletMemoryCachedMetric(ctx, &args, opts...)
			var s GetMonitoringDropletMemoryCachedMetricResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetMonitoringDropletMemoryCachedMetricResultOutput)
}

type GetMonitoringDropletMemoryCachedMetricOutputArgs struct {
}

func (GetMonitoringDropletMemoryCachedMetricOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMonitoringDropletMemoryCachedMetricArgs)(nil)).Elem()
}

type GetMonitoringDropletMemoryCachedMetricResultOutput struct{ *pulumi.OutputState }

func (GetMonitoringDropletMemoryCachedMetricResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMonitoringDropletMemoryCachedMetricResult)(nil)).Elem()
}

func (o GetMonitoringDropletMemoryCachedMetricResultOutput) ToGetMonitoringDropletMemoryCachedMetricResultOutput() GetMonitoringDropletMemoryCachedMetricResultOutput {
	return o
}

func (o GetMonitoringDropletMemoryCachedMetricResultOutput) ToGetMonitoringDropletMemoryCachedMetricResultOutputWithContext(ctx context.Context) GetMonitoringDropletMemoryCachedMetricResultOutput {
	return o
}

func (o GetMonitoringDropletMemoryCachedMetricResultOutput) Items() MetricsOutput {
	return o.ApplyT(func(v GetMonitoringDropletMemoryCachedMetricResult) Metrics { return v.Items }).(MetricsOutput)
}

func init() {
	pulumi.RegisterOutputType(GetMonitoringDropletMemoryCachedMetricResultOutput{})
}
