// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.VolumesV2
{
    [DigitalOceanNativeResourceType("digitalocean-native:volumes/v2:VolumeSnapshot")]
    public partial class VolumeSnapshot : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A human-readable name for the volume snapshot.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("snapshot")]
        public Output<Outputs.Snapshots?> Snapshot { get; private set; } = null!;

        /// <summary>
        /// A flat array of tag names as strings to be applied to the resource. Tag names may be for either existing or new tags.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a VolumeSnapshot resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VolumeSnapshot(string name, VolumeSnapshotArgs? args = null, CustomResourceOptions? options = null)
            : base("digitalocean-native:volumes/v2:VolumeSnapshot", name, args ?? new VolumeSnapshotArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VolumeSnapshot(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("digitalocean-native:volumes/v2:VolumeSnapshot", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-digitalocean-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VolumeSnapshot resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VolumeSnapshot Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new VolumeSnapshot(name, id, options);
        }
    }

    public sealed class VolumeSnapshotArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A human-readable name for the volume snapshot.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// A flat array of tag names as strings to be applied to the resource. Tag names may be for either existing or new tags.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The ID of the block storage volume.
        /// </summary>
        [Input("volumeId")]
        public Input<string>? VolumeId { get; set; }

        public VolumeSnapshotArgs()
        {
        }
        public static new VolumeSnapshotArgs Empty => new VolumeSnapshotArgs();
    }
}
