// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.Outputs
{

    [OutputType]
    public sealed class Image
    {
        /// <summary>
        /// A time value given in ISO8601 combined date and time format that represents when the image was created.
        /// </summary>
        public readonly string? CreatedAt;
        /// <summary>
        /// An optional free-form text field to describe an image.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The name of a custom image's distribution. Currently, the valid values are  `Arch Linux`, `CentOS`, `CoreOS`, `Debian`, `Fedora`, `Fedora Atomic`,  `FreeBSD`, `Gentoo`, `openSUSE`, `RancherOS`, `Rocky Linux`, `Ubuntu`, and `Unknown`.  Any other value will be accepted but ignored, and `Unknown` will be used in its place.
        /// </summary>
        public readonly CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.ImageDistribution? Distribution;
        /// <summary>
        /// A string containing information about errors that may occur when importing
        ///  a custom image.
        /// </summary>
        public readonly string? ErrorMessage;
        /// <summary>
        /// A unique number that can be used to identify and reference a specific image.
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// The minimum disk size in GB required for a Droplet to use this image.
        /// </summary>
        public readonly int? MinDiskSize;
        /// <summary>
        /// The display name that has been given to an image.  This is what is shown in the control panel and is generally a descriptive title for the image in question.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// This is a boolean value that indicates whether the image in question is public or not. An image that is public is available to all accounts. A non-public image is only accessible from your account.
        /// </summary>
        public readonly bool? Public;
        /// <summary>
        /// This attribute is an array of the regions that the image is available in. The regions are represented by their identifying slug values.
        /// </summary>
        public readonly ImmutableArray<CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.ImageRegionsItem> Regions;
        /// <summary>
        /// The size of the image in gigabytes.
        /// </summary>
        public readonly double? SizeGigabytes;
        /// <summary>
        /// A uniquely identifying string that is associated with each of the DigitalOcean-provided public images. These can be used to reference a public image as an alternative to the numeric id.
        /// </summary>
        public readonly string? Slug;
        /// <summary>
        /// A status string indicating the state of a custom image. This may be `NEW`,
        ///  `available`, `pending`, `deleted`, or `retired`.
        /// </summary>
        public readonly CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.ImageStatus? Status;
        /// <summary>
        /// A flat array of tag names as strings to be applied to the resource. Tag names may be for either existing or new tags.
        /// </summary>
        public readonly ImmutableArray<string> Tags;
        /// <summary>
        /// Describes the kind of image. It may be one of `base`, `snapshot`, `backup`, `custom`, or `admin`. Respectively, this specifies whether an image is a DigitalOcean base OS image, user-generated Droplet snapshot, automatically created Droplet backup, user-provided virtual machine image, or an image used for DigitalOcean managed resources (e.g. DOKS worker nodes).
        /// </summary>
        public readonly CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.ImageType? Type;

        [OutputConstructor]
        private Image(
            string? createdAt,

            string? description,

            CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.ImageDistribution? distribution,

            string? errorMessage,

            int? id,

            int? minDiskSize,

            string? name,

            bool? @public,

            ImmutableArray<CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.ImageRegionsItem> regions,

            double? sizeGigabytes,

            string? slug,

            CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.ImageStatus? status,

            ImmutableArray<string> tags,

            CloudySkySoftware.Pulumi.DigitalOceanNative.ReservedIpsV2.ImageType? type)
        {
            CreatedAt = createdAt;
            Description = description;
            Distribution = distribution;
            ErrorMessage = errorMessage;
            Id = id;
            MinDiskSize = minDiskSize;
            Name = name;
            Public = @public;
            Regions = regions;
            SizeGigabytes = sizeGigabytes;
            Slug = slug;
            Status = status;
            Tags = tags;
            Type = type;
        }
    }
}
