// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.DropletsV2.Outputs
{

    [OutputType]
    public sealed class ListDropletsItems
    {
        public readonly ImmutableArray<Outputs.Droplet> Droplets;
        public readonly Outputs.PageLinks? Links;
        public readonly Outputs.MetaMeta MetaValue;

        [OutputConstructor]
        private ListDropletsItems(
            ImmutableArray<Outputs.Droplet> droplets,

            Outputs.PageLinks? links,

            Outputs.MetaMeta meta)
        {
            Droplets = droplets;
            Links = links;
            MetaValue = meta;
        }
    }
}
