// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-digitalocean-native/sdk/go/dgtlocn/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetVolumeSnapshotsById(ctx *pulumi.Context, args *GetVolumeSnapshotsByIdArgs, opts ...pulumi.InvokeOption) (*GetVolumeSnapshotsByIdResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVolumeSnapshotsByIdResult
	err := ctx.Invoke("digitalocean-native:volumes/v2:getVolumeSnapshotsById", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetVolumeSnapshotsByIdArgs struct {
	// Either the ID of an existing snapshot. This will be an integer for a Droplet snapshot or a string for a volume snapshot.
	SnapshotId string `pulumi:"snapshotId"`
}

type GetVolumeSnapshotsByIdResult struct {
	Snapshot *Snapshots `pulumi:"snapshot"`
}

func GetVolumeSnapshotsByIdOutput(ctx *pulumi.Context, args GetVolumeSnapshotsByIdOutputArgs, opts ...pulumi.InvokeOption) GetVolumeSnapshotsByIdResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVolumeSnapshotsByIdResultOutput, error) {
			args := v.(GetVolumeSnapshotsByIdArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv GetVolumeSnapshotsByIdResult
			secret, err := ctx.InvokePackageRaw("digitalocean-native:volumes/v2:getVolumeSnapshotsById", args, &rv, "", opts...)
			if err != nil {
				return GetVolumeSnapshotsByIdResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(GetVolumeSnapshotsByIdResultOutput)
			if secret {
				return pulumi.ToSecret(output).(GetVolumeSnapshotsByIdResultOutput), nil
			}
			return output, nil
		}).(GetVolumeSnapshotsByIdResultOutput)
}

type GetVolumeSnapshotsByIdOutputArgs struct {
	// Either the ID of an existing snapshot. This will be an integer for a Droplet snapshot or a string for a volume snapshot.
	SnapshotId pulumi.StringInput `pulumi:"snapshotId"`
}

func (GetVolumeSnapshotsByIdOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVolumeSnapshotsByIdArgs)(nil)).Elem()
}

type GetVolumeSnapshotsByIdResultOutput struct{ *pulumi.OutputState }

func (GetVolumeSnapshotsByIdResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVolumeSnapshotsByIdResult)(nil)).Elem()
}

func (o GetVolumeSnapshotsByIdResultOutput) ToGetVolumeSnapshotsByIdResultOutput() GetVolumeSnapshotsByIdResultOutput {
	return o
}

func (o GetVolumeSnapshotsByIdResultOutput) ToGetVolumeSnapshotsByIdResultOutputWithContext(ctx context.Context) GetVolumeSnapshotsByIdResultOutput {
	return o
}

func (o GetVolumeSnapshotsByIdResultOutput) Snapshot() SnapshotsPtrOutput {
	return o.ApplyT(func(v GetVolumeSnapshotsByIdResult) *Snapshots { return v.Snapshot }).(SnapshotsPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVolumeSnapshotsByIdResultOutput{})
}
