// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.AppsV2.Outputs
{

    [OutputType]
    public sealed class AppAlertProgressStep
    {
        public readonly string? EndedAt;
        public readonly string? Name;
        public readonly Outputs.AppAlertProgressStepReason? Reason;
        public readonly string? StartedAt;
        public readonly Pulumi.DigitalOceanNative.AppsV2.AppAlertProgressStepStatus? Status;

        [OutputConstructor]
        private AppAlertProgressStep(
            string? endedAt,

            string? name,

            Outputs.AppAlertProgressStepReason? reason,

            string? startedAt,

            Pulumi.DigitalOceanNative.AppsV2.AppAlertProgressStepStatus? status)
        {
            EndedAt = endedAt;
            Name = name;
            Reason = reason;
            StartedAt = startedAt;
            Status = status;
        }
    }
}
