// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOceanNative.AppsV2.Outputs
{

    /// <summary>
    /// The match configuration for the rule.
    /// </summary>
    [OutputType]
    public sealed class AppIngressSpecRuleMatch
    {
        /// <summary>
        /// The path to match on.
        /// </summary>
        public readonly Outputs.AppIngressSpecRuleStringMatch Path;

        [OutputConstructor]
        private AppIngressSpecRuleMatch(Outputs.AppIngressSpecRuleStringMatch path)
        {
            Path = path;
        }
    }
}
