# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload, Awaitable
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'GetProjectsDefaultProperties',
    'AwaitableGetProjectsDefaultProperties',
    'get_projects_default',
    'get_projects_default_output',
]

@pulumi.output_type
class GetProjectsDefaultProperties:
    def __init__(__self__, project=None):
        if project and not isinstance(project, dict):
            raise TypeError("Expected argument 'project' to be a dict")
        pulumi.set(__self__, "project", project)

    @property
    @pulumi.getter
    def project(self) -> Optional['outputs.Project']:
        return pulumi.get(self, "project")


class AwaitableGetProjectsDefaultProperties(GetProjectsDefaultProperties):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetProjectsDefaultProperties(
            project=self.project)


def get_projects_default(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetProjectsDefaultProperties:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('digitalocean-native:projects/v2:getProjectsDefault', __args__, opts=opts, typ=GetProjectsDefaultProperties).value

    return AwaitableGetProjectsDefaultProperties(
        project=pulumi.get(__ret__, 'project'))
def get_projects_default_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetProjectsDefaultProperties]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('digitalocean-native:projects/v2:getProjectsDefault', __args__, opts=opts, typ=GetProjectsDefaultProperties)
    return __ret__.apply(lambda __response__: GetProjectsDefaultProperties(
        project=pulumi.get(__response__, 'project')))
