// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.DigitalOceanNative.DatabasesV2
{
    [DigitalOceanNativeResourceType("digitalocean-native:databases/v2:DatabasesUser")]
    public partial class DatabasesUser : global::Pulumi.CustomResource
    {
        [Output("mysqlSettings")]
        public Output<Outputs.MysqlSettings?> MysqlSettings { get; private set; } = null!;

        /// <summary>
        /// The name of a database user.
        /// </summary>
        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        /// <summary>
        /// A randomly generated password for the database user.
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// For MongoDB clusters, set to `true` to create a read-only user.
        /// This option is not currently supported for other database engines.
        /// </summary>
        [Output("readonly")]
        public Output<bool?> Readonly { get; private set; } = null!;

        /// <summary>
        /// A string representing the database user's role. The value will be either
        /// "primary" or "normal".
        /// </summary>
        [Output("role")]
        public Output<CloudySkySoftware.Pulumi.DigitalOceanNative.DatabasesV2.DatabaseUserRole?> Role { get; private set; } = null!;

        [Output("user")]
        public Output<Outputs.DatabaseUser> User { get; private set; } = null!;


        /// <summary>
        /// Create a DatabasesUser resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DatabasesUser(string name, DatabasesUserArgs args, CustomResourceOptions? options = null)
            : base("digitalocean-native:databases/v2:DatabasesUser", name, args ?? new DatabasesUserArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DatabasesUser(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("digitalocean-native:databases/v2:DatabasesUser", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-digitalocean-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DatabasesUser resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DatabasesUser Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DatabasesUser(name, id, options);
        }
    }

    public sealed class DatabasesUserArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A unique identifier for a database cluster.
        /// </summary>
        [Input("databaseClusterUuid")]
        public Input<string>? DatabaseClusterUuid { get; set; }

        [Input("mysqlSettings")]
        public Input<Inputs.MysqlSettingsArgs>? MysqlSettings { get; set; }

        /// <summary>
        /// The name of a database user.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// A randomly generated password for the database user.
        /// </summary>
        [Input("password")]
        public Input<string>? Password { get; set; }

        /// <summary>
        /// For MongoDB clusters, set to `true` to create a read-only user.
        /// This option is not currently supported for other database engines.
        /// </summary>
        [Input("readonly")]
        public Input<bool>? Readonly { get; set; }

        /// <summary>
        /// A string representing the database user's role. The value will be either
        /// "primary" or "normal".
        /// </summary>
        [Input("role")]
        public Input<CloudySkySoftware.Pulumi.DigitalOceanNative.DatabasesV2.DatabaseUserRole>? Role { get; set; }

        public DatabasesUserArgs()
        {
        }
        public static new DatabasesUserArgs Empty => new DatabasesUserArgs();
    }
}
