// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-digitalocean-native/sdk/go/dgtlocn/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDomainsRecord(ctx *pulumi.Context, args *LookupDomainsRecordArgs, opts ...pulumi.InvokeOption) (*LookupDomainsRecordResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDomainsRecordResult
	err := ctx.Invoke("digitalocean-native:domains/v2:getDomainsRecord", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupDomainsRecordArgs struct {
	// The name of the domain itself.
	DomainName string `pulumi:"domainName"`
	// The unique identifier of the domain record.
	DomainRecordId string `pulumi:"domainRecordId"`
}

type LookupDomainsRecordResult struct {
	DomainRecord *DomainRecord `pulumi:"domainRecord"`
}

func LookupDomainsRecordOutput(ctx *pulumi.Context, args LookupDomainsRecordOutputArgs, opts ...pulumi.InvokeOption) LookupDomainsRecordResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDomainsRecordResultOutput, error) {
			args := v.(LookupDomainsRecordArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupDomainsRecordResult
			secret, err := ctx.InvokePackageRaw("digitalocean-native:domains/v2:getDomainsRecord", args, &rv, "", opts...)
			if err != nil {
				return LookupDomainsRecordResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupDomainsRecordResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupDomainsRecordResultOutput), nil
			}
			return output, nil
		}).(LookupDomainsRecordResultOutput)
}

type LookupDomainsRecordOutputArgs struct {
	// The name of the domain itself.
	DomainName pulumi.StringInput `pulumi:"domainName"`
	// The unique identifier of the domain record.
	DomainRecordId pulumi.StringInput `pulumi:"domainRecordId"`
}

func (LookupDomainsRecordOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDomainsRecordArgs)(nil)).Elem()
}

type LookupDomainsRecordResultOutput struct{ *pulumi.OutputState }

func (LookupDomainsRecordResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDomainsRecordResult)(nil)).Elem()
}

func (o LookupDomainsRecordResultOutput) ToLookupDomainsRecordResultOutput() LookupDomainsRecordResultOutput {
	return o
}

func (o LookupDomainsRecordResultOutput) ToLookupDomainsRecordResultOutputWithContext(ctx context.Context) LookupDomainsRecordResultOutput {
	return o
}

func (o LookupDomainsRecordResultOutput) DomainRecord() DomainRecordPtrOutput {
	return o.ApplyT(func(v LookupDomainsRecordResult) *DomainRecord { return v.DomainRecord }).(DomainRecordPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDomainsRecordResultOutput{})
}
