// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-digitalocean-native/sdk/go/dgtlocn/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDomainsRecord(ctx *pulumi.Context, args *GetDomainsRecordArgs, opts ...pulumi.InvokeOption) (*GetDomainsRecordResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDomainsRecordResult
	err := ctx.Invoke("digitalocean-native:domains/v2:getDomainsRecord", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDomainsRecordArgs struct {
	// The name of the domain itself.
	DomainName string `pulumi:"domainName"`
	// The unique identifier of the domain record.
	DomainRecordId string `pulumi:"domainRecordId"`
}

type GetDomainsRecordResult struct {
	Items GetDomainsRecordProperties `pulumi:"items"`
}

func GetDomainsRecordOutput(ctx *pulumi.Context, args GetDomainsRecordOutputArgs, opts ...pulumi.InvokeOption) GetDomainsRecordResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDomainsRecordResult, error) {
			args := v.(GetDomainsRecordArgs)
			r, err := GetDomainsRecord(ctx, &args, opts...)
			var s GetDomainsRecordResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDomainsRecordResultOutput)
}

type GetDomainsRecordOutputArgs struct {
	// The name of the domain itself.
	DomainName pulumi.StringInput `pulumi:"domainName"`
	// The unique identifier of the domain record.
	DomainRecordId pulumi.StringInput `pulumi:"domainRecordId"`
}

func (GetDomainsRecordOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainsRecordArgs)(nil)).Elem()
}

type GetDomainsRecordResultOutput struct{ *pulumi.OutputState }

func (GetDomainsRecordResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainsRecordResult)(nil)).Elem()
}

func (o GetDomainsRecordResultOutput) ToGetDomainsRecordResultOutput() GetDomainsRecordResultOutput {
	return o
}

func (o GetDomainsRecordResultOutput) ToGetDomainsRecordResultOutputWithContext(ctx context.Context) GetDomainsRecordResultOutput {
	return o
}

func (o GetDomainsRecordResultOutput) Items() GetDomainsRecordPropertiesOutput {
	return o.ApplyT(func(v GetDomainsRecordResult) GetDomainsRecordProperties { return v.Items }).(GetDomainsRecordPropertiesOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDomainsRecordResultOutput{})
}
