// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function listActions(args?: ListActionsArgs, opts?: pulumi.InvokeOptions): Promise<outputs.actions.v2.ListActionsItems> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("digitalocean-native:actions/v2:listActions", {
    }, opts);
}

export interface ListActionsArgs {
}
export function listActionsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<outputs.actions.v2.ListActionsItems> {
    return pulumi.output(listActions(opts))
}
